import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common'; import { JwtService } from '@nestjs/jwt'; import { InjectRepository } from '@nestjs/typeorm'; import * as argon2 from 'argon2'; import { createHash, randomBytes } from 'crypto'; import { Repository } from 'typeorm'; import { RegisterDto } from './dto/auth.dto'; import { Organization } from '../database/entities/organization.entity'; import { RefreshToken } from '../database/entities/refresh-token.entity'; import { Role, User } from '../database/entities/user.entity'; import { AuditLog } from '../database/entities/audit-log.entity';
@Injectable() export class AuthService {
  constructor(@InjectRepository(User) private users: Repository<User>, @InjectRepository(Organization) private orgs: Repository<Organization>, @InjectRepository(RefreshToken) private tokens: Repository<RefreshToken>, @InjectRepository(AuditLog) private audit: Repository<AuditLog>, private jwt: JwtService) {}
  async register(dto: RegisterDto, ip?: string) { if (await this.users.exists({ where: { email: dto.email.toLowerCase() } })) throw new ConflictException('Email is already registered'); const organization = await this.orgs.save(this.orgs.create({ name: dto.organizationName, industry: dto.industry ?? null })); const user = await this.users.save(this.users.create({ name: dto.name, email: dto.email.toLowerCase(), passwordHash: await argon2.hash(dto.password), role: Role.SECURITY_ADMIN, organizationId: organization.id })); user.organization = organization; await this.log(user.id, 'AUTH.REGISTERED', ip); return this.issue(user); }
  async login(email: string, password: string, ip?: string) { const user = await this.users.createQueryBuilder('user').addSelect('user.passwordHash').leftJoinAndSelect('user.organization', 'organization').where('user.email = :email', { email: email.toLowerCase() }).getOne(); if (!user || !(await argon2.verify(user.passwordHash, password))) throw new UnauthorizedException('Invalid email or password'); await this.log(user.id, 'AUTH.LOGGED_IN', ip); return this.issue(user); }
  async refresh(value: string, ip?: string) { const hash = this.hash(value); const token = await this.tokens.findOne({ where: { token: hash }, relations: { user: { organization: true } } }); if (!token || token.expiresAt < new Date()) { if (token) await this.tokens.remove(token); throw new UnauthorizedException('Refresh token is invalid or expired'); } await this.tokens.remove(token); await this.log(token.user.id, 'AUTH.TOKEN_REFRESHED', ip); return this.issue(token.user); }
  async logout(value: string, ip?: string) { const token = await this.tokens.findOne({ where: { token: this.hash(value) }, relations: { user: true } }); if (token) { await this.log(token.userId, 'AUTH.LOGGED_OUT', ip); await this.tokens.remove(token); } }
  async me(id: string) { const user = await this.users.findOne({ where: { id }, relations: { organization: true } }); if (!user) throw new UnauthorizedException(); return this.sanitize(user); }
  private async issue(user: User) { const payload = { sub: user.id, role: user.role, organizationId: user.organizationId }; const accessToken = await this.jwt.signAsync(payload, { secret: process.env.JWT_SECRET, expiresIn: '15m' }); const refreshToken = randomBytes(48).toString('base64url'); await this.tokens.save(this.tokens.create({ userId: user.id, token: this.hash(refreshToken), expiresAt: new Date(Date.now() + 7 * 86400000) })); return { user: this.sanitize(user), accessToken, refreshToken, expiresIn: 900 }; }
  private sanitize(user: User) { return { id: user.id, name: user.name, email: user.email, role: user.role, organization: user.organization ? { id: user.organization.id, name: user.organization.name, industry: user.organization.industry } : null }; }
  private hash(value: string) { return createHash('sha256').update(value).digest('hex'); } private log(userId: string, action: string, ip?: string) { return this.audit.save(this.audit.create({ userId, action, ipAddress: ip ?? null, metadata: null })); }
}
