'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '../../lib/auth-store';
import { authApi } from '../../lib/auth.api';
import { devicesApi } from '../../lib/devices.api';
type Summary = { totalDevices:number; onlineDevices:number; offlineDevices:number; operatingSystems:Record<string,number>; agentVersions:Record<string,number> };
export default function Dashboard() {
  const router=useRouter(); const {user,accessToken,clear}=useAuthStore(); const [summary,setSummary]=useState<Summary|null>(null); const [error,setError]=useState('');
  useEffect(()=>{if(accessToken) devicesApi.summary(accessToken).then(setSummary).catch(e=>setError(e.message));},[accessToken]);
  if(!user) return <main className="auth"><section className="card"><h1>Session required</h1><button className="button" onClick={()=>router.push('/login')}>Sign in</button></section></main>;
  const canManageUsers=user.role==='SECURITY_ADMIN'||user.role==='SUPER_ADMIN';
  return <div className="shell"><aside className="sidebar"><p className="brand">SENTINELX</p><nav><span>Dashboard</span><Link href="/dashboard/organization">Organization</Link>{user.role==='SUPER_ADMIN'&&<Link href="/dashboard/organizations">Organizations</Link>}{canManageUsers&&<Link href="/dashboard/users">Users</Link>}<Link href="/dashboard/devices">Devices</Link></nav></aside><main className="main"><header className="topbar"><div><strong>{user.organization?.name}</strong><div>{user.role.replace('_',' ')}</div></div><button className="button" style={{width:'auto'}} onClick={async()=>{await authApi.logout().catch(()=>undefined);clear();router.push('/login')}}>Sign out</button></header><h1>Monitoring dashboard</h1>{error&&<p className="error" role="alert">{error}</p>}<div className="metric-grid">{[['Total devices',summary?.totalDevices],['Online',summary?.onlineDevices],['Offline',summary?.offlineDevices],['Operating systems',summary&&Object.keys(summary.operatingSystems).length]].map(([label,value])=><section className="metric-card" key={String(label)}><span>{label}</span><strong>{value??'—'}</strong></section>)}</div><section className="dashboard-grid"><div className="card"><h2>Device status</h2>{summary&&<><div className="bar-row"><span>Online</span><div className="bar"><i style={{width:`${summary.totalDevices?summary.onlineDevices/summary.totalDevices*100:0}%`}}/></div><b>{summary.onlineDevices}</b></div><div className="bar-row"><span>Offline</span><div className="bar offline-bar"><i style={{width:`${summary.totalDevices?summary.offlineDevices/summary.totalDevices*100:0}%`}}/></div><b>{summary.offlineDevices}</b></div></>}</div><div className="card"><h2>Operating systems</h2>{summary?Object.entries(summary.operatingSystems).map(([name,count])=><div className="bar-row" key={name}><span>{name}</span><div className="bar"><i style={{width:`${summary.totalDevices?count/summary.totalDevices*100:0}%`}}/></div><b>{count}</b></div>):<p>Loading…</p>}</div></section><section className="empty">Welcome, {user.name}. Device health and telemetry are based on the latest enrolled-agent data. Open <Link href="/dashboard/devices">Devices</Link> to inspect an endpoint.</section></main></div>;
}
