'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { useAuthStore } from '../../../../lib/auth-store';
import { devicesApi } from '../../../../lib/devices.api';
type Telemetry={id:string;recordedAt:string;cpuUsage:number;memoryUsage:number;diskUsage:number;uptimeSeconds:number};
type Device={hostname:string;agentId:string;operatingSystem:string;osVersion:string;architecture:string;ipAddress:string|null;agentVersion:string;firstSeen:string;lastSeen:string|null;status:string;latestTelemetry:Telemetry[]};
const formatUptime=(seconds:number)=>{const days=Math.floor(seconds/86400);const hours=Math.floor(seconds%86400/3600);const minutes=Math.floor(seconds%3600/60);return `${days}d ${hours}h ${minutes}m`;};
function HealthChart({label,value,color='var(--accent)'}:{label:string;value:number;color?:string}){return <div className="health-chart"><div><span>{label}</span><strong>{value.toFixed(1)}%</strong></div><div className="health-track"><i style={{width:`${Math.min(100,Math.max(0,value))}%`,background:color}}/></div></div>}
export default function DeviceDetail(){const {id}=useParams<{id:string}>();const {accessToken}=useAuthStore();const [device,setDevice]=useState<Device|null>(null);const [error,setError]=useState('');useEffect(()=>{if(accessToken&&id)devicesApi.detail(accessToken,id).then(value=>setDevice(value as unknown as Device)).catch(e=>setError(e.message));},[accessToken,id]);if(error)return <main className="main"><Link href="/dashboard/devices">← Devices</Link><p className="error">{error}</p></main>;const latest=device?.latestTelemetry?.[0];return <main className="main"><Link href="/dashboard/devices">← Devices</Link><h1>{device?.hostname??'Device details'}</h1>{!device?<p>Loading…</p>:<><div className="detail-header"><div><span className="muted">Agent ID</span><code>{device.agentId}</code></div><span className={device.status==='ONLINE'?'online':'offline'}>{device.status}</span></div><section className="detail-grid"><div className="card"><h2>Device information</h2><dl className="info-grid"><dt>Operating system</dt><dd>{device.operatingSystem}</dd><dt>OS version</dt><dd>{device.osVersion}</dd><dt>Architecture</dt><dd>{device.architecture}</dd><dt>IP address</dt><dd>{device.ipAddress??'Not reported'}</dd><dt>Agent version</dt><dd>{device.agentVersion}</dd><dt>First seen</dt><dd>{new Date(device.firstSeen).toLocaleString()}</dd><dt>Last seen</dt><dd>{device.lastSeen?new Date(device.lastSeen).toLocaleString():'Never'}</dd></dl></div><div className="card"><h2>System health</h2>{latest?<><HealthChart label="CPU usage" value={latest.cpuUsage}/><HealthChart label="Memory usage" value={latest.memoryUsage} color="#7ba7ff"/><HealthChart label="Disk usage" value={latest.diskUsage} color="#f7c66b"/><p className="muted">Uptime: {formatUptime(Number(latest.uptimeSeconds))}</p></>:<p className="muted">No telemetry received yet.</p>}</div></section><section className="card"><h2>Recent telemetry</h2>{device.latestTelemetry.length===0?<p className="muted">No telemetry records available.</p>:<div className="telemetry-list">{device.latestTelemetry.map(row=><div className="telemetry-row" key={row.id}><span>{new Date(row.recordedAt).toLocaleString()}</span><span>CPU {row.cpuUsage.toFixed(1)}%</span><span>RAM {row.memoryUsage.toFixed(1)}%</span><span>Disk {row.diskUsage.toFixed(1)}%</span><span>{formatUptime(Number(row.uptimeSeconds))}</span></div>)}</div>}</section></>}</main>}
