import { useAuthStore } from './auth-store';
const base = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';
export type Device = { id:string; agentId:string; hostname:string; operatingSystem:string; osVersion:string; architecture:string; status:'ONLINE'|'OFFLINE'; agentVersion:string; lastSeen:string|null; organizationId:string };
async function refreshSession() { const res=await fetch(`${base}/auth/refresh`,{method:'POST',body:'{}',credentials:'include',headers:{'Content-Type':'application/json'}}); if(!res.ok)return null; const session=await res.json(); useAuthStore.getState().setSession({accessToken:session.accessToken,user:session.user}); return session as {accessToken:string}; }
export async function request(path:string, token:string, init:RequestInit={}, retried=false) { const res=await fetch(`${base}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers??{})},credentials:'include'}); if(res.status===401&&!retried){const session=await refreshSession();if(session)return request(path,session.accessToken,init,true);useAuthStore.getState().clear();throw new Error('Your session expired. Please sign in again.');} if(!res.ok) throw new Error((await res.json().catch(()=>null))?.error?.message??'Request failed'); return res.json(); }
export type DeviceFilters={page?:number;limit?:number;status?:string;os?:string;search?:string};
export type TelemetryRecord = { id:string; agentId:string; cpuUsage:number; memoryTotal:number|string; memoryUsed:number|string; memoryUsage:number|null; diskTotal:number|string; diskUsed:number|string; diskUsage:number|null; uptimeSeconds:number|string; recordedAt:string; createdAt:string };
export type DeviceDetail = Device & { latestTelemetry:TelemetryRecord[]; firstSeen:string; ipAddress:string|null; credentialRevokedAt:string|null; createdAt:string; updatedAt:string };
export const devicesApi={ list:(token:string, filters:DeviceFilters={})=>{const qs=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)]));return request(`/agents?${qs}`,token) as Promise<{items:Device[];total:number;totalPages:number;page:number;limit:number}>;}, detail:(token:string,id:string)=>request(`/agents/${id}`,token) as Promise<DeviceDetail>, telemetry:(token:string,id:string,options:{limit?:number;latest?:boolean}={})=>{const qs=new URLSearchParams(Object.entries(options).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));return request(`/agents/${id}/telemetry?${qs}`,token) as Promise<{items:TelemetryRecord[];total:number;limit:number}>;}, enrollmentToken:(token:string)=>request('/agents/enrollment-token',token,{method:'POST'}) as Promise<{token:string;apiUrl:string;expiresAt:string}>, revokeEnrollmentToken:(token:string)=>request('/agents/enrollment-token',token,{method:'DELETE'}) };
